### PR TITLE
fix(docs): transpile reference guide on save

### PR DESCRIPTION
**Pull request by SebCodesTheWeb**
This adds back the previous yarn watch-docs command, renamed as transpile:watch. It rebuilds the reference docs page when one makes a difference and saves the file so one can see the changes immediately instead of having to re transpile the entire docs

### CODE REVIEW

**Comment by magnusohlin** [comment]
@SebCodesTheWeb Great stuff, thanks! Could you do a branch rename please, it is not pulling down with that name for some reason.

**Comment by magnusohlin** [comment]
It might be an issue as well that the PR is actually done via a fork, not sure here.

**Comment by ilija-** [comment]
AMAZING !

**Comment by SebCodesTheWeb** [comment]
Moved to : https://github.com/mediatool/northlight/pull/128

**Pull request closed without merging**
