### PR TITLE
fix(framework): add year to date option to date-range-picker

### PR DESCRIPTION
**Pull request by SebCodesTheWeb**
https://github.com/mediatool/northlight/assets/90923099/582bcd18-ab4b-4e65-ae6f-d73de7707157

### CODE REVIEW

**Review by magnusohlin — CHANGES_REQUESTED** [review]
Would love it if it could be visible without scroll. Specially since people might not know the setting exists

**Comment by SebCodesTheWeb** [comment]
Screenshot 2023-10-25 at 13 32 53
Moved it up

**Comment by magnusohlin** [comment]
Nice, can we also fix so that all options are title-case - looking at you sneaky "Last month"

**Comment by SebCodesTheWeb** [comment]
Screenshot 2023-10-25 at 13 38 28
@magnusohlin haha yes it has been fixed

**Pull request merged**
