### PR TITLE
fix(framework): fix scrolling

### PR DESCRIPTION
**Pull request by PaoloGiraudi**

### CODE REVIEW

**Comment by orestisrodriguez** [comment]
@PaoloGiraudi 👀

**Comment by SebCodesTheWeb** [comment]
A surprise to be sure, but a welcome one

**Review by SebCodesTheWeb — APPROVED** [review]
LGTM

**Comment by SebCodesTheWeb** [comment]
haha just kidding, this is amazing, not only because I'm happy to finally see a PR by Paolo again, but also because it's actually a good PR, I was frustrated with the scrolling but was to lazy to fix it.

**Pull request merged**
